/**
 * Word (.docx) builder for report exports.
 *
 * Document structure (single section, PageBreak paragraphs between pages):
 *
 *   ┌──────────────────────────────────────┐
 *   │  Title page (centred)                │
 *   │  - Round label                       │
 *   │  - Report title                      │
 *   │  - Type + date                       │
 *   │  - Confidential notice               │
 *   ├──────────────────────────────────────┤ ← PageBreak
 *   │  Contents                            │
 *   │  1. Section name                     │
 *   │  2. Section name  ...                │
 *   ├──────────────────────────────────────┤ ← PageBreak
 *   │  [Content sections from report]      │
 *   │  Heading1 / Heading2 / Heading3      │
 *   │  Normal paragraphs / lists           │
 *   ├──────────────────────────────────────┤ ← PageBreak
 *   │  Key Themes / Evidence / Audit Trail │
 *   └──────────────────────────────────────┘
 *
 *   Footer on every page: "Confidential. Generated by the MindMuse Consultant Platform"
 */

import {
  Document,
  Packer,
  Paragraph,
  TextRun,
  HeadingLevel,
  AlignmentType,
  PageBreak,
  Footer,
  type FileChild,
} from "docx";
import type { ContentBlock } from "@/lib/report-content-blocks";
import type {
  ExportSection,
  ExportTheme,
  ExportThemeMember,
  ExportConsultation,
  ExportAuditEvent,
  ExportAuditMilestone,
  ExportConnection,
} from "@/lib/report-export-content";

// ─── Inline text parsing ──────────────────────────────────────────────────────
// Converts markdown **bold** and _italic_ markers into TextRun children.
// Handles plain text, bold, italic. Does not recurse (no bold-italic combos).

function parseInlineRuns(text: string): TextRun[] {
  // Split on **bold** and _italic_ markers
  const parts = text.split(/(\*\*[^*]+\*\*|_[^_]+_)/g);
  return parts
    .filter(Boolean)
    .map((part) => {
      if (part.startsWith("**") && part.endsWith("**")) {
        return new TextRun({ text: part.slice(2, -2), bold: true });
      }
      if (part.startsWith("_") && part.endsWith("_")) {
        return new TextRun({ text: part.slice(1, -1), italics: true });
      }
      return new TextRun({ text: part });
    });
}

// ─── Block → Paragraph(s) ────────────────────────────────────────────────────

function blockToParagraphs(block: ContentBlock): Paragraph[] {
  switch (block.type) {
    case "heading1":
      return [
        new Paragraph({
          heading: HeadingLevel.HEADING_1,
          children: [new TextRun({ text: block.text })],
        }),
      ];

    case "heading2":
      return [
        new Paragraph({
          heading: HeadingLevel.HEADING_2,
          children: [new TextRun({ text: block.text })],
        }),
      ];

    case "heading3":
      return [
        new Paragraph({
          heading: HeadingLevel.HEADING_3,
          children: [new TextRun({ text: block.text })],
        }),
      ];

    case "prose":
      return [
        new Paragraph({
          children: parseInlineRuns(block.text),
        }),
      ];

    case "bullet":
      return block.items.map(
        (item) =>
          new Paragraph({
            bullet: { level: 0 },
            children: parseInlineRuns(item),
          })
      );

    case "numbered":
      return block.items.map(
        (item, i) =>
          new Paragraph({
            children: [new TextRun({ text: `${i + 1}. ${item}` })],
          })
      );
  }
}

// ─── Structured data → Paragraph(s) ──────────────────────────────────────────

function themeToLabel(status: ExportTheme["status"]): string {
  switch (status) {
    case "accepted": return "Accepted";
    case "draft": return "Pending Review";
    case "rejected": return "Rejected";
  }
}

function memberToParagraphs(member: ExportThemeMember): Paragraph[] {
  const paras: Paragraph[] = [];
  paras.push(
    new Paragraph({
      indent: { left: 360 },
      children: [
        new TextRun({ text: "\u2013 ", color: "888888" }),
        new TextRun({ text: member.label }),
        member.sourceConsultationTitle
          ? new TextRun({ text: `  (${member.sourceConsultationTitle})`, color: "888888", italics: true })
          : new TextRun({ text: "" }),
      ],
      spacing: { after: 40 },
    })
  );
  if (member.description) {
    paras.push(
      new Paragraph({
        indent: { left: 540 },
        children: [new TextRun({ text: member.description, italics: true, color: "666666" })],
        spacing: { after: 40 },
      })
    );
  }
  return paras;
}

function themesToParagraphs(themes: ExportTheme[]): Paragraph[] {
  const paras: Paragraph[] = [];
  for (const theme of themes) {
    paras.push(
      new Paragraph({
        children: [
          new TextRun({ text: theme.label, bold: true }),
          new TextRun({ text: `  [${themeToLabel(theme.status)}]`, color: "666666" }),
        ],
        spacing: { after: 80 },
      })
    );
    if (theme.description) {
      paras.push(
        new Paragraph({
          children: [new TextRun({ text: theme.description, italics: true, color: "444444" })],
          spacing: { after: 40 },
        })
      );
    }
    if (theme.members.length > 0) {
      for (const member of theme.members) {
        paras.push(...memberToParagraphs(member));
      }
    }
    // trailing spacer after each group
    paras.push(new Paragraph({ children: [], spacing: { after: 120 } }));
  }
  return paras;
}

function connectionsToParagraphs(connections: ExportConnection[]): Paragraph[] {
  return connections.map((conn) => {
    const label = `${conn.fromLabel}  \u2192  ${conn.toLabel}`;
    const sub = [conn.connectionType, conn.notes].filter(Boolean).join("  \u00b7  ");
    return new Paragraph({
      bullet: { level: 0 },
      children: [
        new TextRun({ text: label }),
        ...(sub ? [new TextRun({ text: `  \u2014  ${sub}`, color: "888888" })] : []),
      ],
      spacing: { after: 80 },
    });
  });
}

function consultationsToParagraphs(consultations: ExportConsultation[]): Paragraph[] {
  const paras: Paragraph[] = [];
  for (const c of consultations) {
    paras.push(
      new Paragraph({
        children: [new TextRun({ text: c.title, bold: true })],
        spacing: { after: 60 },
      })
    );
    if (c.date) {
      paras.push(
        new Paragraph({
          children: [
            new TextRun({
              text: new Date(c.date).toLocaleDateString("en-GB", { dateStyle: "long" }),
              color: "555555",
            }),
          ],
          spacing: { after: 40 },
        })
      );
    }
    if (c.people.length > 0) {
      paras.push(
        new Paragraph({
          children: [new TextRun({ text: `Attendees: ${c.people.join(", ")}` })],
          spacing: { after: 160 },
        })
      );
    } else {
      paras.push(new Paragraph({ children: [], spacing: { after: 120 } }));
    }
  }
  return paras;
}

function auditSessionsToParagraphs(sessions: ExportAuditEvent[]): Paragraph[] {
  const paras: Paragraph[] = [
    new Paragraph({
      heading: HeadingLevel.HEADING_2,
      children: [new TextRun({ text: "Consultation sessions" })],
    }),
  ];

  for (const session of sessions) {
    const dateStr = new Date(session.date).toLocaleDateString("en-GB", {
      dateStyle: "medium",
    });
    paras.push(
      new Paragraph({
        bullet: { level: 0 },
        children: [
          new TextRun({ text: session.title, bold: true }),
          new TextRun({ text: `  —  ${dateStr}`, color: "555555" }),
        ],
        spacing: { after: 80 },
      })
    );
  }

  return paras;
}

function auditMilestonesToParagraphs(
  milestones: ExportAuditMilestone[]
): Paragraph[] {
  const paras: Paragraph[] = [
    new Paragraph({
      heading: HeadingLevel.HEADING_2,
      children: [new TextRun({ text: "Process record" })],
    }),
  ];

  for (const milestone of milestones) {
    const dateStr = new Date(milestone.createdAt).toLocaleDateString("en-GB", {
      dateStyle: "medium",
    });
    const countSuffix = milestone.count > 1 ? ` (×${milestone.count})` : "";
    paras.push(
      new Paragraph({
        bullet: { level: 0 },
        children: [
          new TextRun({ text: milestone.label + countSuffix, bold: true }),
          new TextRun({ text: `  —  ${dateStr}`, color: "555555" }),
        ],
        spacing: { after: 80 },
      })
    );
  }

  return paras;
}

function auditTrailToParagraphs(
  sessions: ExportAuditEvent[],
  milestones: ExportAuditMilestone[]
): Paragraph[] {
  const paras: Paragraph[] = [];

  if (sessions.length > 0) {
    paras.push(...auditSessionsToParagraphs(sessions));
  }

  if (milestones.length > 0) {
    if (paras.length > 0) {
      paras.push(new Paragraph({ children: [], spacing: { after: 80 } }));
    }
    paras.push(...auditMilestonesToParagraphs(milestones));
  }

  return paras;
}

// ─── Section → FileChild[] ────────────────────────────────────────────────────

function sectionToChildren(section: ExportSection): FileChild[] {
  const children: FileChild[] = [];

  if (section.isPageBreak) {
    children.push(new Paragraph({ children: [new PageBreak()] }));
  }

  if (section.heading) {
    children.push(
      new Paragraph({
        heading: HeadingLevel.HEADING_1,
        children: [new TextRun({ text: section.heading })],
      })
    );
  }

  for (const block of section.blocks) {
    children.push(...blockToParagraphs(block));
  }

  if (section.data) {
    switch (section.data.kind) {
      case "themes":
        children.push(...themesToParagraphs(section.data.themes));
        break;
      case "evidence":
        children.push(...consultationsToParagraphs(section.data.consultations));
        break;
      case "audit":
        children.push(
          ...auditTrailToParagraphs(
            section.data.sessions,
            section.data.milestones
          )
        );
        break;
      case "connections":
        children.push(...connectionsToParagraphs(section.data.connections));
        break;
    }
  }

  return children;
}

// ─── Title page ───────────────────────────────────────────────────────────────

function buildTitlePage(opts: {
  title: string | null;
  roundLabel: string;
  generatedAt: string;
  artifactType: string;
}): FileChild[] {
  const { title, roundLabel, generatedAt, artifactType } = opts;

  const artifactTypeLabels: Record<string, string> = {
    summary: "Consultation Summary",
    report: "Board-Pack Report",
    email: "Evidence Email",
  };
  const typeLabel = artifactTypeLabels[artifactType] ?? artifactType;
  const dateStr = new Date(generatedAt).toLocaleDateString("en-GB", { dateStyle: "long" });

  return [
    // Vertical spacing before title
    new Paragraph({ children: [], spacing: { before: 2400 } }),

    new Paragraph({
      alignment: AlignmentType.CENTER,
      children: [
        new TextRun({ text: roundLabel, size: 24, color: "555555" }),
      ],
      spacing: { after: 240 },
    }),

    new Paragraph({
      alignment: AlignmentType.CENTER,
      children: [
        new TextRun({
          text: title ?? "Untitled Report",
          bold: true,
          size: 48,
        }),
      ],
      spacing: { after: 480 },
    }),

    new Paragraph({
      alignment: AlignmentType.CENTER,
      children: [new TextRun({ text: typeLabel, size: 24, color: "444444" })],
      spacing: { after: 120 },
    }),

    new Paragraph({
      alignment: AlignmentType.CENTER,
      children: [new TextRun({ text: `Generated ${dateStr}`, size: 22, color: "666666" })],
      spacing: { after: 960 },
    }),

    new Paragraph({
      alignment: AlignmentType.CENTER,
      children: [
        new TextRun({
          text: "CONFIDENTIAL",
          bold: true,
          size: 20,
          color: "888888",
          allCaps: true,
        }),
      ],
      spacing: { after: 200 },
    }),

    new Paragraph({
      alignment: AlignmentType.CENTER,
      children: [
        new TextRun({
          text: "This document contains privileged and confidential information intended solely for the named recipient.",
          size: 18,
          color: "999999",
          italics: true,
        }),
      ],
    }),
  ];
}

// ─── Contents page ────────────────────────────────────────────────────────────

function buildContentsPage(sections: ExportSection[]): FileChild[] {
  const namedSections = sections.filter((s) => s.heading !== null);

  const children: FileChild[] = [
    new Paragraph({ children: [new PageBreak()] }),
    new Paragraph({
      heading: HeadingLevel.HEADING_1,
      children: [new TextRun({ text: "Contents" })],
    }),
  ];

  namedSections.forEach((section, i) => {
    children.push(
      new Paragraph({
        children: [
          new TextRun({ text: `${i + 1}.  `, bold: true }),
          new TextRun({ text: section.heading! }),
        ],
        spacing: { after: 120 },
      })
    );
  });

  return children;
}

// ─── Confidential footer ──────────────────────────────────────────────────────

function buildFooter(): Footer {
  return new Footer({
    children: [
      new Paragraph({
        alignment: AlignmentType.CENTER,
        children: [
          new TextRun({
            text: "Confidential. Generated by the MindMuse Consultant Platform",
            size: 16,
            color: "999999",
            italics: true,
          }),
        ],
      }),
    ],
  });
}

// ─── Main builder ─────────────────────────────────────────────────────────────

export interface DocxExportOptions {
  title: string | null;
  roundLabel: string;
  generatedAt: string;
  artifactType: string;
  sections: ExportSection[];
}

/**
 * Build a .docx Buffer from ExportSections.
 * Returns a Node.js Buffer suitable for an HTTP response.
 */
export async function buildDocxBuffer(opts: DocxExportOptions): Promise<Buffer> {
  const { title, roundLabel, generatedAt, artifactType, sections } = opts;

  const footer = buildFooter();

  const children: FileChild[] = [
    ...buildTitlePage({ title, roundLabel, generatedAt, artifactType }),
    ...buildContentsPage(sections),
    ...sections.flatMap(sectionToChildren),
  ];

  const doc = new Document({
    title: title ?? "Untitled Report",
    creator: "ConsultantPlatform",
    description: `${roundLabel} — exported report`,
    sections: [
      {
        children,
        footers: { default: footer },
      },
    ],
  });

  return Packer.toBuffer(doc);
}
