FROM oven/bun:1

WORKDIR /app

COPY db/package.migrations.json ./package.json
RUN bun install --production

COPY db ./db
COPY drizzle ./drizzle
COPY lib/env.ts ./lib/env.ts

RUN chmod +x ./db/scripts/run-migrations.sh

CMD ["./db/scripts/run-migrations.sh"]
