FROM oven/bun:1

WORKDIR /app

COPY package.json bun.lock ./
RUN bun install --frozen-lockfile --production

COPY db ./db
COPY drizzle ./drizzle
COPY drizzle.config.ts ./drizzle.config.ts
COPY lib/env.ts ./lib/env.ts

RUN chmod +x ./db/scripts/run-migrations.sh

CMD ["./db/scripts/run-migrations.sh"]
